name: Create Release
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Install jq tool
      run: |
        sudo apt-get update
        sudo apt-get install texlive-xetex
    - uses: pandoc/actions/setup@v1
      with:
        version: 2.19
    - run: make pdf
    - uses: ncipollo/release-action@v1
      name: Upload PDF File to GitHub
      with:
        artifacts: output.pdf
